### ISSUE TITLE
No module named 'smoter.data.datasets'.

### ISSUE THREAD

**Issue by jxd31415** [HengLan/SMOT#2]
Thank you so much for providing a new direction for the MOT community! When trying to run your code, I encountered two problems that I would like the author to answer. 1. The datasets file is missing from smoter/data/. 2. Two images in the bensmot are invalid.

**Comment by backyardknights** [comment]
I previously encountered your problem 1, and I eliminated this error by moving a copy of the datasets folder from the built root directory to the corresponding folder. However, I don't think this solves the problem. Currently, running train_net.py can start the 0th iteration, but it shows that /smoter/data/smoter_dataset_dataloader.py cannot find the bensmot images, causing the program to interrupt and stop training. I'm not sure if the issue lies in your problem 1 or in smoter_dataset_dataloader.py itself.

**Comment by backyardknights** [comment]
I apologize for any inconvenience. I would like to know if you have resolved the issue and successfully replicated SMOT.

**Comment by jxd31415** [comment]
I haven't solved the above problem and am still waiting for the author's reply.

**Comment by Nathan-Li123** [comment]
Sorry for the late reply. Due to an error in the .gitignore file, there was an issue with missing files in the data folder. I have corrected this, and the corresponding files should now be available in the smoter/data folder. 
As for the second question, I don't actually understand what 'invalid images' mean, can you provide some specific error reports or detailed descriptions?

**Comment by Nathan-Li123** [comment]
> I previously encountered your problem 1, and I eliminated this error by moving a copy of the datasets folder from the built root directory to the corresponding folder. However, I don't think this solves the problem. Currently, running train_net.py can start the 0th iteration, but it shows that /smoter/data/smoter_dataset_dataloader.py cannot find the bensmot images, causing the program to interrupt and stop training. I'm not sure if the issue lies in your problem 1 or in smoter_dataset_dataloader.py itself.

I hope the changes to the repository will solve your problem, if not, please feel free to let me know.
